# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0
version = 1

[[annotations]]
path = [
 "mix.lock",
 "NOTICE",
 "test/fixture/proc_self_mountinfo/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# Generated files
[[annotations]]
path = [
 "test/fixture/ops-fail.fw",
 "test/fixture/ops-status.fw",
 "test/fixture/ops.fw",
 "test/fixture/ops-execute-unsafe.fw",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
